---
- name: Install nodejs and npm
  apt:
    pkg:
      - nodejs
      - npm
    state: present

- name: Install Forever (to run our Node.js app).
  npm: name=forever global=yes state=present

- name: Install npm modules required by our app.
  npm: name={{ item }} global=yes state=present 
  with_items: "{{ node_npm_modules }}"
